// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Matze {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    [uFrame.Attributes.ComponentId(1)]
    public partial class Orc : uFrame.ECS.Components.GroupItem {
        
        private Sword _Sword;
        
        private Shield _Shield;
        
        private Health _Health;
        
        public Sword Sword {
            get {
                return _Sword;
            }
            set {
                _Sword = value;
            }
        }
        
        public Shield Shield {
            get {
                return _Shield;
            }
            set {
                _Shield = value;
            }
        }
        
        public Health Health {
            get {
                return _Health;
            }
            set {
                _Health = value;
            }
        }
        
        public override int ComponentId {
            get {
                return 1;
            }
        }
    }
}
