// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Matze {
    using Matze;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    
    
    [uFrame.Attributes.EventId(1)]
    public partial class OrcClicked : object {
        
        [UnityEngine.SerializeField()]
        private Int32 _OrcId;
        
        public Int32 OrcId {
            get {
                return _OrcId;
            }
            set {
                _OrcId = value;
            }
        }
    }
}
