// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Matze {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DamageSystemOrcClickedHandler {
        
        public Orc Group;
        
        private Matze.OrcClicked _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private object ActionNode14_message = default( System.Object );
        
        private int ActionNode16_a = default( System.Int32 );
        
        private int ActionNode16_b = default( System.Int32 );
        
        private int IntNode17 = 10;
        
        private int ActionNode16_Result = default( System.Int32 );
        
        private object ActionNode18_message = default( System.Object );
        
        public Matze.OrcClicked Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode14_message = Event.OrcId;
            // ActionNode
            while (this.DebugInfo("e7435b70-65ac-4a3c-a72d-ec3428824984","a367f592-055f-4cb0-94ea-7ef4c799f4e3", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.DebugLibrary.LogMessage
            uFrame.ECS.Actions.DebugLibrary.LogMessage(ActionNode14_message);
            ActionNode16_a = Group.Health.health;
            ActionNode16_b = IntNode17;
            // ActionNode
            while (this.DebugInfo("a367f592-055f-4cb0-94ea-7ef4c799f4e3","858c4df5-70bc-4d8a-b548-dc7a66023b01", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.IntLibrary.Subtract
            ActionNode16_Result = uFrame.ECS.Actions.IntLibrary.Subtract(ActionNode16_a, ActionNode16_b);
            // SetVariableNode
            while (this.DebugInfo("858c4df5-70bc-4d8a-b548-dc7a66023b01","9a5e0681-c283-471d-839e-526eac9dbbc2", this) == 1) yield return null;
            Group.Health.health = (System.Int32)ActionNode16_Result;
            ActionNode18_message = ActionNode16_Result;
            // ActionNode
            while (this.DebugInfo("9a5e0681-c283-471d-839e-526eac9dbbc2","0fa2094c-f598-416a-96b2-412e8c36b1e3", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.DebugLibrary.LogMessage
            uFrame.ECS.Actions.DebugLibrary.LogMessage(ActionNode18_message);
            yield break;
        }
    }
}
