// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Matze {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DamageSystemOrcClickedHandler {
        
        public Health clickedOrc;
        
        private Matze.OrcClicked _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private int ActionNode15_a = default( System.Int32 );
        
        private int ActionNode15_b = default( System.Int32 );
        
        private int IntNode16 = 10;
        
        private int ActionNode15_Result = default( System.Int32 );
        
        private object ActionNode17_message = default( System.Object );
        
        public Matze.OrcClicked Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode15_a = clickedOrc.health;
            ActionNode15_b = IntNode16;
            // ActionNode
            while (this.DebugInfo("d2545072-59e1-4a15-8a17-e19c6c7464e0","a8936c94-0795-4283-9f2e-bb1238a1a9b0", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.IntLibrary.Subtract
            ActionNode15_Result = uFrame.ECS.Actions.IntLibrary.Subtract(ActionNode15_a, ActionNode15_b);
            // SetVariableNode
            while (this.DebugInfo("a8936c94-0795-4283-9f2e-bb1238a1a9b0","577597d9-24b6-4b17-a76d-0221ff6d69ae", this) == 1) yield return null;
            clickedOrc.health = (System.Int32)ActionNode15_Result;
            ActionNode17_message = ActionNode15_Result;
            // ActionNode
            while (this.DebugInfo("577597d9-24b6-4b17-a76d-0221ff6d69ae","3190afbd-6bf4-46ac-a14c-a5820a0f93f5", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.DebugLibrary.LogMessage
            uFrame.ECS.Actions.DebugLibrary.LogMessage(ActionNode17_message);
            yield break;
        }
    }
}
