// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Matze {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class InputSystemOnMouseDownHandler {
        
        public Orc Source;
        
        private uFrame.ECS.UnityUtilities.MouseDownDispatcher _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private object ActionNode10_message = default( System.Object );
        
        private string StringNode11 = "orc clicked";
        
        private Matze.OrcClicked PublishEventNode18_Result = default( Matze.OrcClicked );
        
        public uFrame.ECS.UnityUtilities.MouseDownDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode10_message = StringNode11;
            // ActionNode
            while (this.DebugInfo("2765c9ed-2821-4b2a-ac06-83f6ece5e855","85661589-9238-40f7-b8a3-8df48ab0a5d2", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.DebugLibrary.LogMessage
            uFrame.ECS.Actions.DebugLibrary.LogMessage(ActionNode10_message);
            // PublishEventNode
            while (this.DebugInfo("85661589-9238-40f7-b8a3-8df48ab0a5d2","d2545072-59e1-4a15-8a17-e19c6c7464e0", this) == 1) yield return null;
            var PublishEventNode18_Event = new OrcClicked();
            PublishEventNode18_Event.clickedOrc = Source.EntityId;
            System.Publish(PublishEventNode18_Event);
            PublishEventNode18_Result = PublishEventNode18_Event;
            yield break;
        }
    }
}
